const SAVE_KEY = 'chips_save_v1';
const SUITS = ['clubs', 'diamonds', 'hearts', 'spades'];
const RANKS = [{ label: '2', value: 2 }, { label: '3', value: 3 }, { label: '4', value: 4 }, { label: '5', value: 5 }, { label: '6', value: 6 }, { label: '7', value: 7 }, { label: '8', value: 8 }, { label: '9', value: 9 }, { label: '10', value: 10 }, { label: 'J', value: 11 }, { label: 'Q', value: 12 }, { label: 'K', value: 13 }, { label: 'A', value: 14 }];
const DIFFICULTY = { easy: { dealerName: 'THE HOUSE', threshold: 15 }, medium: { dealerName: 'THE HOUSE', threshold: 17 }, hard: { dealerName: 'THE HOUSE', threshold: 19 }, impossible: { dealerName: 'THE HOUSE', threshold: 21 } };
let state = null;
function createDeck() { return SUITS.flatMap((suit, suitIndex) => RANKS.map((rank, rankIndex) => ({ id: `${suit}-${rank.label}`, suit, rank: rank.label, value: rank.value, order: suitIndex * 13 + rankIndex }))); }
function shuffleDeck(deck) { const shuffled = [...deck]; for (let index = shuffled.length - 1; index > 0; index -= 1) { const swapIndex = Math.floor(Math.random() * (index + 1)); [shuffled[index], shuffled[swapIndex]] = [shuffled[swapIndex], shuffled[index]]; } return shuffled; }
function sortCards(cards) { return [...cards].sort((a, b) => a.order - b.order); }
function drawCard() { return state.deck.pop(); }
function evaluateHand(cards) { const combinations = []; function choose(start, hand) { if (hand.length === Math.min(5, cards.length)) { combinations.push(hand); return; } for (let index = start; index < cards.length; index += 1) choose(index + 1, [...hand, cards[index]]); } choose(0, []); return combinations.reduce((best, hand) => { const counts = Object.values(hand.reduce((map, card) => { map[card.value] = (map[card.value] || 0) + 1; return map; }, {})).sort((a, b) => b - a); const values = hand.map(card => card.value).sort((a, b) => b - a); const suits = new Set(hand.map(card => card.suit)); const unique = [...new Set(values)].sort((a, b) => b - a); const straight = unique.length === 5 && (unique[0] - unique[4] === 4 || unique.join(',') === '14,5,4,3,2'); const score = suits.size === 1 && straight ? 8 : counts[0] === 4 ? 7 : counts[0] === 3 && counts[1] === 2 ? 6 : suits.size === 1 ? 5 : straight ? 4 : counts[0] === 3 ? 3 : counts[0] === 2 && counts[1] === 2 ? 2 : counts[0] === 2 ? 1 : 0; return score > best.score || (score === best.score && values.join('') > best.values.join('')) ? { score, values, label: ['high card', 'pair', 'two pair', 'three of a kind', 'straight', 'flush', 'full house', 'four of a kind', 'straight flush'][score] } : best; }, { score: -1, values: [] }); }
function freshState() { return { playerName: '', difficulty: 'medium', bankroll: 1000, wager: 20, deck: [], playerCards: [], dealerCards: [], communityCards: [], pot: 0, street: 'pre-flop', roundActive: false, stats: { rounds: 0, wins: 0, losses: 0, pushes: 0 }, unlocks: { holdem: true, blackjack: false }, lore: { currentEvent: null, history: [] } }; }
function saveGame() { localStorage.setItem(SAVE_KEY, JSON.stringify(state)); }
function loadGame() { try { const saved = JSON.parse(localStorage.getItem(SAVE_KEY)); return saved ? { ...freshState(), ...saved, stats: { ...freshState().stats, ...(saved.stats || {}) }, unlocks: { ...freshState().unlocks, ...(saved.unlocks || {}) } } : freshState(); } catch { return freshState(); } }
function showScreen(id) { document.querySelectorAll('.screen').forEach(screen => screen.classList.toggle('hidden', screen.id !== id)); }
function setDialogue(text) { document.getElementById('dealer-dialogue').textContent = `THE DEALER: ${text}`; }
function renderCard(card, hidden = false) { if (hidden) return '<div class="card hidden-card" aria-label="Hidden card">?</div>'; const red = ['diamonds', 'hearts'].includes(card.suit) ? ' red' : ''; return `<div class="card${red}" title="${card.suit} ${card.rank}">${card.rank}<small>${card.suit[0].toUpperCase()}</small></div>`; }
function renderTable() { document.getElementById('dealer-name').textContent = DIFFICULTY[state.difficulty].dealerName; document.getElementById('player-label').textContent = state.playerName.toUpperCase(); document.getElementById('bankroll').textContent = state.bankroll.toLocaleString(); document.getElementById('pot-size').textContent = state.pot.toLocaleString(); document.getElementById('street-label').textContent = state.street.replace('-', ' ').toUpperCase(); document.getElementById('dealer-cards').innerHTML = state.dealerCards.map((card, index) => renderCard(card, state.roundActive && index === 1)).join(''); document.getElementById('player-cards').innerHTML = state.playerCards.map(card => renderCard(card)).join(''); document.getElementById('community-cards').innerHTML = state.communityCards.map(card => renderCard(card)).join(''); renderActions(); }
function renderActions() { const actions = document.getElementById('table-actions'); if (!state.roundActive) { actions.innerHTML = '<button data-action="deal">DEAL NEW HAND</button>'; return; } actions.innerHTML = '<button data-action="fold">FOLD</button><button data-action="check">CHECK</button><button data-action="call">CALL</button><button data-action="raise">RAISE</button>'; actions.querySelector('[data-action="check"]').disabled = state.pot > state.wager; }
function dealHand() { if (state.bankroll < state.wager) { setDialogue('You do not have enough chips to sit at this table.'); return; } state.deck = shuffleDeck(createDeck()); state.playerCards = [drawCard(), drawCard()]; state.dealerCards = [drawCard(), drawCard()]; state.communityCards = [drawCard(), drawCard(), drawCard()]; state.pot = state.wager * 2; state.bankroll -= state.wager; state.street = 'flop'; state.roundActive = true; document.getElementById('round-message').textContent = ''; setDialogue('The first three cards are on the felt. Decide whether you trust the shape of your luck.'); saveGame(); renderTable(); }
function settle(result, message) { state.roundActive = false; state.stats.rounds += 1; state.stats[{ win: 'wins', loss: 'losses', push: 'pushes' }[result]] += 1; if (result === 'win') state.bankroll += state.pot; if (result === 'push') state.bankroll += state.wager; setDialogue(message); document.getElementById('round-message').textContent = result === 'win' ? 'YOU TAKE THE POT.' : result === 'push' ? 'THE POT RETURNS TO YOU.' : 'THE HOUSE KEEPS THE POT.'; saveGame(); renderTable(); }
function resolveHand() { const playerHand = evaluateHand([...state.playerCards, ...state.communityCards]); const dealerHand = evaluateHand([...state.dealerCards, ...state.communityCards]); if (playerHand.score > dealerHand.score || (playerHand.score === dealerHand.score && playerHand.values.join('') > dealerHand.values.join(''))) return settle('win', `Your ${playerHand.label} beats the dealer's ${dealerHand.label}. The house looks away.`); if (playerHand.score === dealerHand.score && playerHand.values.join('') === dealerHand.values.join('')) return settle('push', `Both hands show ${playerHand.label}. Nobody blinks.`); return settle('loss', `The dealer's ${dealerHand.label} beats your ${playerHand.label}. The table remembers.`); }
function handleAction(action) { if (action === 'deal') return dealHand(); if (!state.roundActive) return; if (action === 'fold') return settle('loss', 'You folded. A sensible choice, perhaps.'); if (action === 'check' || action === 'call') { state.street = 'turn'; state.communityCards.push(drawCard()); setDialogue('One more card. The distance between courage and stupidity is narrowing.'); if (action === 'call') state.pot += state.wager; } if (action === 'raise') { const amount = Math.max(10, Number(document.getElementById('raise-amount').value) || 10); if (amount > state.bankroll) return setDialogue('You cannot wager chips that are not in front of you.'); state.bankroll -= amount; state.pot += amount * 2; state.wager += amount; state.street = 'river'; state.communityCards.push(drawCard()); setDialogue('You raised. The dealer accepts your invitation.'); } if (state.communityCards.length >= 5) resolveHand(); saveGame(); renderTable(); }
function resetRun() { state = freshState(); localStorage.removeItem(SAVE_KEY); showScreen('name-screen'); }
document.addEventListener('DOMContentLoaded', () => { state = loadGame(); document.getElementById('name-form').addEventListener('submit', event => { event.preventDefault(); state.playerName = document.getElementById('player-name').value.trim(); if (!state.playerName) return; document.getElementById('selected-player').textContent = state.playerName.toUpperCase(); showScreen('difficulty-screen'); }); document.querySelectorAll('[data-difficulty]').forEach(button => button.addEventListener('click', () => { state.difficulty = button.dataset.difficulty; document.getElementById('table-difficulty').textContent = state.difficulty.toUpperCase(); showScreen('game-select-screen'); })); document.querySelector('[data-game="holdem"]').addEventListener('click', () => { showScreen('table-screen'); setDialogue('Welcome to the long table. Deal when you are ready.'); renderTable(); saveGame(); }); document.getElementById('table-actions').addEventListener('click', event => handleAction(event.target.dataset.action)); document.getElementById('new-run').addEventListener('click', resetRun); });
window.Chips = { createDeck, shuffleDeck, sortCards, evaluateHand };
